from psychopy import visual, core
from psychopy.hardware import keyboard
from page import Page


def initPages(win, log_obj):
    # --- Initialize components for each Routine ---
    Title = visual.TextStim(
        win=win,
        name="Title",
        text="Intro page",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=0.0,
    )
    SubTitle = visual.TextStim(
        win=win,
        name="SubTitle",
        text="Controls and example pic",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=-1.0,
    )
    arrows = visual.ImageStim(
        win=win,
        name="arrows",
        image="/home/rfox/PhD/Term1_22-23_Experiements/experimentEagle22/images/SeekPng.com_arrow-keys-png_3271603.png",
        mask=None,
        anchor="center",
        ori=0.0,
        pos=(0, 0),
        size=(0.5, 0.5),
        color=[1, 1, 1],
        colorSpace="rgb",
        opacity=None,
        flipHoriz=False,
        flipVert=False,
        texRes=128.0,
        interpolate=True,
        depth=-2.0,
    )
    wasd = visual.ImageStim(
        win=win,
        name="wasd",
        image="/home/rfox/PhD/Term1_22-23_Experiements/experimentEagle22/images/SeekPng.com_wasd-png_1791627.png",
        mask=None,
        anchor="center",
        ori=0.0,
        pos=(0, 0),
        size=(0.5, 0.5),
        color=[1, 1, 1],
        colorSpace="rgb",
        opacity=None,
        flipHoriz=False,
        flipVert=False,
        texRes=128.0,
        interpolate=True,
        depth=-3.0,
    )
    Sim_image = visual.ImageStim(
        win=win,
        name="Sim",
        image="/home/rfox/PhD/Term1_22-23_Experiements/experimentEagle22/images/Simulator.png",
        mask=None,
        anchor="center",
        ori=0.0,
        pos=(0, 0),
        size=(0.5, 0.5),
        color=[1, 1, 1],
        colorSpace="rgb",
        opacity=None,
        flipHoriz=False,
        flipVert=False,
        texRes=128.0,
        interpolate=True,
        depth=-4.0,
    )
    button = visual.ButtonStim(
        win,
        text="Click here or press spacebar to continue",
        font="Arvo",
        pos=(0, 0),
        letterHeight=0.05,
        size=None,
        borderWidth=0.0,
        fillColor="darkgrey",
        borderColor=None,
        color="white",
        colorSpace="rgb",
        opacity=None,
        bold=True,
        italic=False,
        padding=None,
        anchor="center",
        name="button",
    )
    button.buttonClock = core.Clock()
    key_resp = keyboard.Keyboard()

    intro_page = Page(
        "intro_page",
        log_obj,
        [Title, SubTitle, arrows, wasd, Sim_image, button, key_resp],
    )

    # --- Initialize components for Routine "Start_Page" ---
    Start_Info = visual.TextStim(
        win=win,
        name="Start_Info",
        text="Any text\n\nincluding line breaks",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=0.0,
    )
    button_2 = visual.ButtonStim(
        win,
        text="Click here or hit Space bar",
        font="Arvo",
        pos=(0, 0),
        letterHeight=0.05,
        size=None,
        borderWidth=0.0,
        fillColor="darkgrey",
        borderColor=None,
        color="white",
        colorSpace="rgb",
        opacity=None,
        bold=True,
        italic=False,
        padding=None,
        anchor="center",
        name="button_2",
    )
    button_2.buttonClock = core.Clock()
    key_resp_2 = keyboard.Keyboard()

    start_page = Page("start_page", log_obj, [Start_Info, button_2, key_resp_2])

    # --- Initialize components for Routine "Simulation" ---

    Sim = Page("Sim", log_obj, [])

    # --- Initialize components for Routine "Safety_Judgements" ---
    Question = visual.TextStim(
        win=win,
        name="Question",
        text="Any text\n\nincluding line breaks",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=0.0,
    )
    Vehicle_image = visual.ImageStim(
        win=win,
        name="Vehicle_image",
        image=None,
        mask=None,
        anchor="center",
        ori=0.0,
        pos=(0, 0),
        size=(0.5, 0.5),
        color=[1, 1, 1],
        colorSpace="rgb",
        opacity=None,
        flipHoriz=False,
        flipVert=False,
        texRes=128.0,
        interpolate=True,
        depth=-1.0,
    )
    Sub_Question = visual.TextStim(
        win=win,
        name="Sub_Question",
        text="Any text\n\nincluding line breaks",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=-2.0,
    )
    slider = visual.Slider(
        win=win,
        name="slider",
        startValue=None,
        size=(1.0, 0.1),
        pos=(0, -0.4),
        units=None,
        labels=None,
        ticks=(1, 2, 3, 4, 5),
        granularity=0.0,
        style="rating",
        styleTweaks=(),
        opacity=None,
        labelColor="LightGray",
        markerColor="Red",
        lineColor="White",
        colorSpace="rgb",
        font="Open Sans",
        labelHeight=0.05,
        flip=False,
        ori=0.0,
        depth=-3,
        readOnly=False,
    )
    Sub_Question_2 = visual.TextStim(
        win=win,
        name="Sub_Question_2",
        text="Any text\n\nincluding line breaks",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=-4.0,
    )
    slider_2 = visual.Slider(
        win=win,
        name="slider_2",
        startValue=None,
        size=(1.0, 0.1),
        pos=(0, -0.4),
        units=None,
        labels=None,
        ticks=(1, 2, 3, 4, 5),
        granularity=0.0,
        style="rating",
        styleTweaks=(),
        opacity=None,
        labelColor="LightGray",
        markerColor="Red",
        lineColor="White",
        colorSpace="rgb",
        font="Open Sans",
        labelHeight=0.05,
        flip=False,
        ori=0.0,
        depth=-5,
        readOnly=False,
    )
    Sub_Question_3 = visual.TextStim(
        win=win,
        name="Sub_Question_3",
        text="Any text\n\nincluding line breaks",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=-6.0,
    )
    slider_3 = visual.Slider(
        win=win,
        name="slider_3",
        startValue=None,
        size=(1.0, 0.1),
        pos=(0, -0.4),
        units=None,
        labels=None,
        ticks=(1, 2, 3, 4, 5),
        granularity=0.0,
        style="rating",
        styleTweaks=(),
        opacity=None,
        labelColor="LightGray",
        markerColor="Red",
        lineColor="White",
        colorSpace="rgb",
        font="Open Sans",
        labelHeight=0.05,
        flip=False,
        ori=0.0,
        depth=-7,
        readOnly=False,
    )

    saftey_judgement_page = Page(
        "saftey_judgement_page",
        log_obj,
        [
            Question,
            Vehicle_image,
            Sub_Question,
            Sub_Question_2,
            Sub_Question_3,
            slider,
            slider_2,
            slider_3,
        ],
    )

    # --- Initialize components for Routine "AV_Judgements" ---
    av_question = visual.TextStim(
        win=win,
        name="AV_Question",
        text="Any text\n\nincluding line breaks",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=0.0,
    )
    car_image = visual.ImageStim(
        win=win,
        name="car_image",
        image="/home/rfox/PhD/Term1_22-23_Experiements/pygame_ped_env/pygame_ped_env/images/Topdown_vehicle_sprites_pack/car.png",
        mask=None,
        anchor="center",
        ori=0.0,
        pos=(0, 0),
        size=(0.5, 0.5),
        color=[1, 1, 1],
        colorSpace="rgb",
        opacity=None,
        flipHoriz=False,
        flipVert=False,
        texRes=128.0,
        interpolate=True,
        depth=-1.0,
    )
    slider_4 = visual.Slider(
        win=win,
        name="slider_4",
        startValue=None,
        size=(1.0, 0.1),
        pos=(0, -0.4),
        units=None,
        labels=None,
        ticks=(1, 2, 3, 4, 5),
        granularity=0.0,
        style="rating",
        styleTweaks=(),
        opacity=None,
        labelColor="LightGray",
        markerColor="Red",
        lineColor="White",
        colorSpace="rgb",
        font="Open Sans",
        labelHeight=0.05,
        flip=False,
        ori=0.0,
        depth=-2,
        readOnly=False,
    )
    car_image_2 = visual.ImageStim(
        win=win,
        name="car_image_2",
        image="/home/rfox/PhD/Term1_22-23_Experiements/pygame_ped_env/pygame_ped_env/images/Topdown_vehicle_sprites_pack/car.png",
        mask=None,
        anchor="center",
        ori=0.0,
        pos=(0, 0),
        size=(0.5, 0.5),
        color=[1, 1, 1],
        colorSpace="rgb",
        opacity=None,
        flipHoriz=False,
        flipVert=False,
        texRes=128.0,
        interpolate=True,
        depth=-3.0,
    )
    slider_5 = visual.Slider(
        win=win,
        name="slider_5",
        startValue=None,
        size=(1.0, 0.1),
        pos=(0, -0.4),
        units=None,
        labels=None,
        ticks=(1, 2, 3, 4, 5),
        granularity=0.0,
        style="rating",
        styleTweaks=(),
        opacity=None,
        labelColor="LightGray",
        markerColor="Red",
        lineColor="White",
        colorSpace="rgb",
        font="Open Sans",
        labelHeight=0.05,
        flip=False,
        ori=0.0,
        depth=-4,
        readOnly=False,
    )

    av_judgement_page = Page(
        "av_judgement_page",
        log_obj,
        [
            av_question,
            car_image,
            car_image_2,
            slider_4,
            slider_5,
        ],
    )

    # --- Initialize components for Routine "Thanks" ---
    Thank_You = visual.TextStim(
        win=win,
        name="Thank_You",
        text="Any text\n\nincluding line breaks",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=0.0,
    )
    Consent_remind = visual.TextStim(
        win=win,
        name="Consent_remind",
        text="Any text\n\nincluding line breaks",
        font="Open Sans",
        pos=(0, 0),
        height=0.05,
        wrapWidth=None,
        ori=0.0,
        color="white",
        colorSpace="rgb",
        opacity=None,
        languageStyle="LTR",
        depth=-1.0,
    )
    button_3 = visual.ButtonStim(
        win,
        text="Click here to Finish Experiment",
        font="Arvo",
        pos=(0, 0),
        letterHeight=0.05,
        size=None,
        borderWidth=0.0,
        fillColor="darkgrey",
        borderColor=None,
        color="white",
        colorSpace="rgb",
        opacity=None,
        bold=True,
        italic=False,
        padding=None,
        anchor="center",
        name="button_3",
    )
    button_3.buttonClock = core.Clock()
    key_resp_3 = keyboard.Keyboard()

    thanks_page = Page(
        "thanks_page", log_obj, [Thank_You, Consent_remind, button_3, key_resp_3]
    )

    return (
        intro_page,
        start_page,
        Sim,
        saftey_judgement_page,
        av_judgement_page,
        thanks_page,
    )
