from psychopy import locale_setup
from psychopy import prefs
from psychopy import (
    sound,
    gui,
    visual,
    core,
    data,
    event,
    logging,
    clock,
    colors,
    layout,
)

# --- Initialize components for Routine "trial" ---
slider = visual.Slider(
    win=win,
    name="slider",
    startValue=None,
    size=(1.0, 0.1),
    pos=(0, -0.4),
    units=None,
    labels=None,
    ticks=(1, 2, 3, 4, 5),
    granularity=0.0,
    style="rating",
    styleTweaks=(),
    opacity=None,
    labelColor="LightGray",
    markerColor="Red",
    lineColor="White",
    colorSpace="rgb",
    font="Open Sans",
    labelHeight=0.05,
    flip=False,
    ori=0.0,
    depth=0,
    readOnly=False,
)
slider_2 = visual.Slider(
    win=win,
    name="slider_2",
    startValue=None,
    size=(1.0, 0.1),
    pos=(0, -0.4),
    units=None,
    labels=None,
    ticks=(1, 2, 3, 4, 5),
    granularity=0.0,
    style="rating",
    styleTweaks=(),
    opacity=None,
    labelColor="LightGray",
    markerColor="Red",
    lineColor="White",
    colorSpace="rgb",
    font="Open Sans",
    labelHeight=0.05,
    flip=False,
    ori=0.0,
    depth=-1,
    readOnly=False,
)
textbox = visual.TextBox2(
    win,
    text="Any text\n\nincluding line breaks",
    font="Open Sans",
    pos=(0, 0),
    letterHeight=0.05,
    size=(None, None),
    borderWidth=2.0,
    color="white",
    colorSpace="rgb",
    opacity=None,
    bold=False,
    italic=False,
    lineSpacing=1.0,
    padding=0.0,
    alignment="center",
    anchor="center",
    fillColor=None,
    borderColor=None,
    flipHoriz=False,
    flipVert=False,
    languageStyle="LTR",
    editable=False,
    name="textbox",
    autoLog=True,
)
text = visual.TextStim(
    win=win,
    name="text",
    text="Any text\n\nincluding line breaks",
    font="Open Sans",
    pos=(0, 0),
    height=0.05,
    wrapWidth=None,
    ori=0.0,
    color="white",
    colorSpace="rgb",
    opacity=None,
    languageStyle="LTR",
    depth=-3.0,
)
img = visual.ImageStim(
    win=win,
    image="",
    mask=None,
    units="",
    pos=(0, 0),
    size=None,
    anchor="center",
    ori=0,
    color=(1, 1, 1),
    colorSpace="rgb",
    contrast=1,
    opacity=None,
    depth=0,
    interpolate=False,
    flipHoriz=False,
    flipVert=False,
    texRes=128,
    name="",
    autoLog=None,
    maskParams=None,
)
